apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: virtlet-pv-claim
spec:
  storageClassName: rook-ceph-block
  volumeMode: Block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

